name: Build and push gen Docker image

on:
  push:
    branches:
      - main
      - dev
    paths:
      - "gen/**"

jobs:
  build-web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push Docker image for gen
        env:
          PROJECT_NAME: ${{ vars.PROJECT_NAME || '<no-name>' }}
        run: |
          TAG=${{ github.sha }}
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            PREFIX="main"
          elif [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            PREFIX="dev"
          fi

          docker build \
            -t ghcr.io/${{ github.repository }}/${PROJECT_NAME}-gen-${PREFIX}:${TAG} ./gen
          docker push ghcr.io/${{ github.repository }}/${PROJECT_NAME}-gen-${PREFIX}:${TAG}

          docker tag ghcr.io/${{ github.repository }}/${PROJECT_NAME}-gen-${PREFIX}:${TAG} ghcr.io/${{ github.repository }}/gen-${PREFIX}:latest
          docker push ghcr.io/${{ github.repository }}/${PROJECT_NAME}-gen-${PREFIX}:latest
